name: Build

on:
    push:
        branches: [master, 1.37.1]
        tags: v*
    pull_request:
        branches: [master]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.x
            - name: Initialize modding environment
              uses: beat-forge/init-beatsaber@v1
              with:
                  token: ${{ github.token }}
                  repo: beat-forge/beatsaber-stripped
            - name: Download Mod Dependencies
              uses: Goobwabber/download-beatmods-deps@1.2
              with:
                  manifest: ${{ github.workspace }}/Source/manifest.json
            - name: Build
              id: Build
              run: dotnet build --configuration Release
            - name: GitStatus
              run: git status
            - name: Echo Filename
              run: echo $BUILDTEXT \($ASSEMBLYNAME\)
              env:
                  BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                  ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: ${{ steps.Build.outputs.filename }}
                  path: ${{ steps.Build.outputs.artifactpath }}
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ./${{ steps.Build.outputs.filename }}.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
